### ISSUE TITLE
Subject of french-language sharing notification is "[user] vous a partagé un fichier avec vous"

### ISSUE THREAD

**Issue by Xyrop** [linagora/linshare#8] opened 2017-09-28 16:27 UTC
And basically, the first "vous" is redundant. And grammar is one of the rare fields where redundancy is not a good thing...

**Comment by Klemele** [comment] 2018-02-26 14:32
Hello!
Thanks for the feedback, we did create a related issue in our private CI and will fix it in the next sprint.
I let this issue open, to avoid redundancy ;).

**Comment by marwanJebahi** [comment] 2019-09-24 13:38
Hello,
The issue is fixed on LinShare 2.1.1 version, here is the changelog:
https://github.com/linagora/linshare/blob/master/CHANGELOG.md#211-2018-05-28-download-link
Regards

**Closed by marwanJebahi** 2019-09-24 13:38 UTC
